version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "nguyenquocthang"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group updates for better organization
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      mui:
        patterns:
          - "@mui/*"
          - "@emotion/*"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "typescript"
      linting:
        patterns:
          - "eslint*"
          - "prettier"
          - "@eslint/*"
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "jest*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "nguyenquocthang"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"

