name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quality-checks:
    name: Code Quality & Type Checking
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Check code formatting
      run: npm run format:check

    - name: Run TypeScript type checking
      run: npm run type-check

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: quality-checks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build
      env:
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        VITE_API_TIMEOUT: 30000
        VITE_APP_NAME: UIT_REG_SYSTEM

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: dist/
        retention-days: 7

  build-status:
    name: Build Status Check
    runs-on: ubuntu-latest
    needs: [quality-checks, build]
    if: always()
    
    steps:
    - name: Check build status
      run: |
        if [ "${{ needs.quality-checks.result }}" != "success" ] || [ "${{ needs.build.result }}" != "success" ]; then
          echo "Build failed!"
          exit 1
        fi
        echo "All checks passed!"

