name: Deploy Preview

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    name: Deploy Preview Environment
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for preview
      run: npm run build
      env:
        VITE_API_BASE_URL: ${{ secrets.PREVIEW_API_BASE_URL }}
        VITE_API_TIMEOUT: 30000
        VITE_APP_NAME: UIT_REG_SYSTEM_PREVIEW

    - name: Deploy to Preview (Vercel/Netlify)
      run: |
        echo "Deploy preview build to your hosting service"
        echo "Build output is in the dist/ directory"
        echo "PR number: ${{ github.event.pull_request.number }}"
      # Uncomment and configure based on your hosting service:
      # For Vercel:
      # - uses: amondnet/vercel-action@v25
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      # For Netlify:
      # - uses: netlify/actions/cli@master
      #   with:
      #     args: deploy --dir=dist --alias=pr-${{ github.event.pull_request.number }}

    - name: Comment PR with preview URL
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 Preview deployment ready!\n\nPreview URL: https://pr-${{ github.event.pull_request.number }}.preview.uit-reg-system.com'
          })

